[package]
name = "simd"
version = "0.1.0"
edition = "2021"




[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = "0.2.16"
log = "0.4"
pretty_env_logger = "0.4.0"



[lib]
name = "utils"
path = "src/lib.rs"